### PR TITLE
Added SPM Support

### PR DESCRIPTION
**Pull request by mohpor**
Signed-off-by: Mohammad Porooshani <porooshani@gmail.com>

### CODE REVIEW

**Comment by Coeur** [comment]
Thank you. Anything else I need to do to "release" it, @mohpor, or it's fine like that on master branch?

**Comment by mohpor** [comment]
@Coeur 
Thanks
Could you please push the tag `1.0.2` for us to be able to use the latest version?

**Comment by mohpor** [comment]
It is fine like this, just a new Tag for the Package manager to find the manifest.

We can still point to `master` but Latest Version is a better approach I think.

**Comment by Coeur** [comment]
I did it all from the GitHub web interface. Hope it's good.

**Comment by mohpor** [comment]
let me check.

**Comment by mohpor** [comment]
Thanks.
It is working as expected.

**Pull request merged**
